apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernets-bootcamp
  labels:
    app: kubernets-bootcamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernets-bootcamp
  template:
    metadata:
      labels:
        app: kubernets-bootcamp
    spec:
      containers:
      - name: kubernets-bootcamp
        image: --image=gcr.io/google-samples/kubernetes-bootcamp:v1
        ports:
        - containerPort: 80
